#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-rng,onMisuse-attribute.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
future:::testme("rng,onMisuse-attribute")
