#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-makeClusterFuture-clusterEvalQ.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
future:::testme("makeClusterFuture-clusterEvalQ")
