#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-check_connection_details.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
future:::testme("check_connection_details")
