## Look for detritus files
testme <- as.environment("testme")
message(sprintf("Looking for detritus connections generated by test %s:", sQuote(testme[["name"]])))

delta <- diff_connections(get_connections(), testme[["testme_connections"]])
if (any(lengths(delta) > 0)) {
  message("Detected detritus connections:")
  print(delta)
}

